#version: '3.8'

services:
  controller:
    build:
      context: ./controller
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./controller:/app
    command: uvicorn api.main:app --host 0.0.0.0 --port 42791 --reload
    ports:
      - "42791:42791"
    env_file:
      - .env
